Fix #966 - Remove Legacy NGSI-v1 from codebase
telefonicaid/iotagent-node-lib pull request #995
Opened 2021-02-24 07:18 UTC by jason-fox

- Remove `config.isCurrentNGSI()` clauses from plugins
- Remove NGSI-v1 Templates
- Remove V1 options from service
- Delete NGSI-V1 classes
- Delete  NGSI-V1 tests
- Convert Keystone and Registry tests to NGSI-v2

2021-02-24 10:00 UTC, jason-fox commented
Related #966

2021-02-24 14:52 UTC, jason-fox commented
@AlvaroVega @fgalan - this is now ready for review. The remaining reduction of 1.5% code coverage **may** still be NGSI-v1 lava code somewhere or it may be that some additional test cases need to be added (particularly around plugins). Either way I wouldn't feel comfortable modifying the code further as part of this PR.

2021-03-05 11:16 UTC, fgalan commented
We are going to start testing on this. To that end, the following (temporal) PRs has been created:

* https://github.com/telefonicaid/iotagent-json/pull/533
* https://github.com/telefonicaid/iotagent-ul/pull/467
* https://github.com/telefonicaid/iotagent-manager/pull/238

While unit tests have gone fine in the IOTA Manager PR, they are failing in IOTA-UL and IOTA-JSON. Looking at the results, it seems it is not the usual glitch in some AMQP tests, but a massive fail. At least 75 tests are failing in the IOTA-UL case and 80 in the IOTA-JSON case.

Maybe I'm doing something wrong... @jason-fox could you have a look, please?

2021-03-05 14:40 UTC, mapedraza commented
> @AlvaroVega @fgalan - this is now ready for review. The remaining reduction of 1.5% code coverage **may** still be NGSI-v1 lava code somewhere or it may be that some additional test cases need to be added (particularly around plugins). Either way I wouldn't feel comfortable modifying the code further as part of this PR.

@jason-fox Just to clarify, the idea is to add more test on a separate PR to increase the code coverage that 1.5% or leave it like this?

2021-03-05 15:00 UTC, jason-fox commented
@mapedraza - leave. All I've done is delete the NGSI-v1 tests and copied over the obvious _tests for non NGSI functionality_ to use  NGSI-v2 requests and responses. I am uncertain where the remaining drop of 1.5% lies - I'm guessing various plugins need to have some NGSI-v1 cleaning to remove dead code, but it could be a coveralls accounting error.

2021-03-05 16:00 UTC, jason-fox commented
>  At least 75 tests are failing in the IOTA-UL case and 80 in the IOTA-JSON case.
> Maybe I'm doing something wrong

The failing tests are provisioned using NGSI-v1. For example

```
      4) should send one update context per measure group to the Context Broker
time=2021-03-05T10:23:21.547Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | msg=An unexpected exception has been raised. Ignoring: AssertionError [ERR_ASSERTION]: Mocks not yet satisfied:
POST http://192.168.1.1:1026/v1/updateContext
```

Has a mock which assumes that the IoT Agent upserts a provisioned device using the **deprecated** `/v1/updateContext` endpoint. This is no longer occurs since the default configuration is NGSI-v2. Just delete the NGSI-v1 tests and re-run with just the tests in the `test/ngsiv2`  folder. (I had to do this with the code in the PR as well)

2021-03-05 16:02 UTC, jason-fox commented
It should be the case that if the NGSI-v1 tests are deleted for IOTA-JSON and IOT-UL there should not be a significant reduction of coverage. If coverage is reduced then some of the NGSI-v1 tests will need to be converted to NGSI-v2.

2021-03-05 16:09 UTC, jason-fox commented
Example run for IOTA-JSON with no NGSI-v1 tests : https://github.com/jason-fox/iotagent-json/runs/2041091462?check_suite_focus=true

2021-05-13 07:14 UTC, fgalan commented
Take into account that https://github.com/telefonicaid/iotagent-node-lib/pull/1034 adds some files related with NGSIv1:

* test/unit/examples/contextRequests/updateContextExpressionPlugin6.json
* test/unit/examples/contextRequests/updateContextExpressionPlugin7.json
* test/unit/examples/contextRequests/updateContextExpressionPlugin8.json

These ones should be removed in this PR upon conflict resolution when updated with master.

2021-05-18 09:05 UTC, jason-fox commented
@fgalan  - seeing no movement on this, I've raised two new PRs to try and reduce the scope.

- If you action #1042 then no tests will run on NGSI-v1, and this PR will reduce by 189 files - coverage has temporarily reduced  by 8% with the test removal since all the legacy NGSI-v1 code remains, but it should return the same as here once this PR is finally actioned and NGSI-v1 deleted.

- If you action #1043 then no references to NGSI-v1 will remain in the docs, and this PR will reduce by 7 files - coverage should remain the same as here.

The following are currently  on your side:

- I assume the blocker on actually updating the code in the library  is here: https://github.com/telefonicaid/iotagent-json/issues/563 so you can successfully run the test suite in the JSON IoT Agent without NGSI-v1. Someone needs to decide whether the code or the test is in error and I guess that is on TEF.

- LightweightM2M test suite is currently broken on **master** - I assume this is due to some IoT Agent node lib change.
https://github.com/telefonicaid/lightweightm2m-iotagent/pull/248 is only failing on  the preparation step of a single test and not within the code itself. Maintaining the test suite is on TEF.

-  Ultralight - https://github.com/telefonicaid/iotagent-ul/pull/487 is open for review 
- Sigfox has no NGSI-v1 tests

2021-05-31 12:15 UTC, fgalan commented
PR https://github.com/telefonicaid/iotagent-node-lib/pull/1054 adds some files related with NGSIv1:

* test/unit/examples/contextRequests/updateContextExpressionPlugin9.json
* test/unit/examples/contextRequests/updateContextExpressionPlugin10.json

These ones should be removed in this PR upon conflict resolution when updated with master.

2021-06-01 14:55 UTC, jason-fox commented
Updated and conflict removed. I'm wondering why are you adding new NGSI-v1 tests - @fgalan

2021-06-01 15:02 UTC, fgalan commented
> Updated and conflict removed. I'm wondering why are you adding new NGSI-v1 tests - @fgalan

In fact we are not adding new NGSI-v1 tests but adjusting the existing ones through the creation of new .json files (not exactly the same ;). While we still having NGIS-v1 functionality in the code, if some NGSI-v1 test breaks it seems to be a good idea to fix it to ensure regression.

2021-07-14 16:07 UTC, fgalan commented
> Sigfox has no NGSI-v1 tests

However, IOTA Sigfox unit tests fails when using this branch (see https://github.com/telefonicaid/sigfox-iotagent/pull/110#issuecomment-880019274). How it can be?

2021-07-15 08:17 UTC, jason-fox commented
I'd missed a couple of `/v1` mocks in the tests - fixed - https://github.com/telefonicaid/sigfox-iotagent/pull/111

2021-07-15 11:16 UTC, fgalan commented
> @fgalan  - seeing no movement on this, I've raised two new PRs to try and reduce the scope.
>
> - If you action #1042 then no tests will run on NGSI-v1, and this PR will reduce by 189 files - coverage has temporarily reduced  by 8% with the test removal since all the legacy NGSI-v1 code remains, but it should return the same as here once this PR is finally actioned and NGSI-v1 deleted.
>
> - If you action #1043 then no references to NGSI-v1 will remain in the docs, and this PR will reduce by 7 files - coverage should remain the same as here.

Now that PR #1043 has merged, I'd suggest:

* To upgrade PR #995 with master (so the scope of the PR would be reduced to just code)
* Close PR #1042 (because at that point it should be equivalent to PR #995 and the later has all the discussion history so it's better to keep it)

@jason-fox what do you think?

2021-07-15 11:21 UTC, jason-fox commented
Done - cba02f1 #1042 has been closed.

2021-07-15 11:49 UTC, fgalan commented on lib/plugins/attributeAlias.js
> -    if (config.isCurrentNgsi()) {
We are removing usages of `isCurrentNgsi()` in IOTA agent code (e.g. PR https://github.com/telefonicaid/iotagent-ul/pull/467 PR  https://github.com/telefonicaid/iotagent-json/pull/533) so I'd suggest to remove also the `isCurrentNgsi()`  function itself in the IOTA Lib.

2021-07-15 14:50 UTC, fgalan commented
At this point 562b6fa changes in coverage are (https://coveralls.io/builds/41398365)

![imagen](https://user-images.githubusercontent.com/1534240/125808583-7f81b21f-67a3-4b61-9388-71ece3bf7474.png)

2021-07-16 11:52 UTC, mapedraza requested changes

2021-07-16 11:52 UTC, mapedraza commented on test/unit/plugins/translation-inPlugins_test.js
> -});
This file does not have an equivalent in NGSI-v2 folder, so it is needed to translate it to v2 version.

2021-07-19 07:18 UTC, jason-fox commented on lib/plugins/multiEntity.js
>  }
Fixed e98d298

2021-07-19 07:19 UTC, jason-fox commented on test/unit/expressions/jexlExpression-test.js
> -});
Fixed c0dc200

2021-07-19 07:20 UTC, jason-fox commented on test/unit/expressions/expression-test.js
> -});
Fixed c0dc200

2021-07-19 07:23 UTC, jason-fox commented on test/unit/mongodb/mongoDBUtils.js
> +    MongoClient.connect(url, { useNewUrlParser: true, useUnifiedTopology: true }, function (err, db) {
Fixed dd4c544

2021-07-19 07:52 UTC, jason-fox commented on test/unit/ngsiService/active-devices-test.js
> -    });
Fixed b966458

2021-07-19 07:54 UTC, jason-fox commented on test/unit/ngsiService/active-devices-test.js
> -    });
Fixed b966458

2021-08-31 12:23 UTC, jason-fox commented
@mapedraza - missing test cases have been added -  this is the current diff (coveralls seems slow today)


### PR

```text
  730 passing (34s)
  11 pending

-------------------------------------|---------|----------|---------|---------|-------------------------------------------------------------------------------------------------------------------
File                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                 
-------------------------------------|---------|----------|---------|---------|-------------------------------------------------------------------------------------------------------------------
All files                            |      81 |    71.19 |   82.96 |   80.91 |                                                                                                                   
 lib                                 |    77.5 |    76.11 |   59.78 |   77.86 |   
```


### Master

```text
  901 passing (41s)
  14 pending

-------------------------------------|---------|----------|---------|---------|-------------------------------------------------------------------------------------------------------------------
File                                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                 
-------------------------------------|---------|----------|---------|---------|-------------------------------------------------------------------------------------------------------------------
All files                            |   81.86 |    72.31 |   84.75 |   81.75 |                                                                                                                   
 lib                                 |    79.4 |    76.67 |   63.44 |   79.77 |     
 ```

2021-09-01 08:34 UTC, mapedraza commented
Hi Jason, thanks for adding all those tests, we are getting close to the previous coverage! ;) 

Reviewing the latests commits, I updated my [previous comment](https://github.com/telefonicaid/iotagent-node-lib/pull/995#issuecomment-906294270) above with the list of pending tests and also resolved the change requested on the thread. However I saw a couple of subtests that still need to be added:

- On File **test/unit/ngsiv2/lazyAndCommands/lazy-devices-test.js**
   - Describe *When a context query arrives to the IoT Agent with a payload that is not JSON*
      - It 'should return an NGSI compliant payload' check is missing 

- On File **test/unit/ngsiService/queryDeviceInformationInCb-test.js**
   - Describe *When the user requests information and there are multiple responses, one of them a failure* is missing

2021-09-01 10:20 UTC, jason-fox commented
@mapedraza - I don't think there is an equivalent NGSI-v2 request to replicate the missing test in **queryDeviceInformationInCb-test.js** - With v2 there is no such error response. if i make the **GET** request `/v2/entities/light1/attrs?attrs=state,dimming&type=Light` and the entity has`state` but not `dimming` then the response is 200 and only `state` is returned. This differs from NGSI-v1 where the body would include error information.

All the other tests are complete and the reduction is now at 0.7% - I guess much of this is removing obscure NGSI-v1 edge case cruft I wouldn't know where to look at.

2021-09-01 10:29 UTC, jason-fox commented
@mapedraza - I don't think there is an equivalent NGSI-v2 request to replicate the missing test in **queryDeviceInformationInCb-test.js** - With v2, if i make the **GET** request `/v2/entities/light1/attrs?attrs=state,dimming&type=Light` and the entity has`state` but not `dimming` then the response is 200 and only `state` is returned. This differs from NGSI-v1 where the body would include error information.

The missing `ATTRIBUTE_NOT_FOUND` constructor can now only be fired by covering line https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/ngsi/entities-NGSI-v2.js#L241 and I'm not sure if that is a legitimate NGSI-v2 response.

All the other tests are complete and the reduction remains at 0.8% - I guess much of this is obscure NGSI-v1 edge cases I wouldn't want to look at.

2021-09-01 11:30 UTC, fgalan commented
> The missing ATTRIBUTE_NOT_FOUND constructor can now only be fired by covering line https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/ngsi/entities-NGSI-v2.js#L241 and I'm not sure if that is a legitimate NGSI-v2 response.

Maybe a warning in the code should be included about this. I mean something like this:

```
            } else if (errorField.code && errorField.code === '404') {
                // FIXME: not sure if this is a legitimate case in NGSI-v2. Should be checked and removed if no longer needed
                callback(new errors.AttributeNotFound());
            } else {
```

2021-09-01 11:35 UTC, fgalan commented
> All the other tests are complete and the reduction remains at 0.7% - I guess much of this is obscure NGSI-v1 edge cases I wouldn't want to look at.

In the case it can help, this is the current (at b1758c3) breakdown (https://coveralls.io/builds/42573501):

![imagen](https://user-images.githubusercontent.com/1534240/131664640-ee0ce5a8-8b97-4da5-aa3f-1a09516030b5.png)

2021-09-01 14:39 UTC, jason-fox commented
I'm fairly positive that the following should work:

### entities-NGSI-v2.js

```diff
         } else if (response && body && response.statusCode === 404) {
             logger.info(
                 context,
                 'Received the following response from the CB:\n\n%s\n\n',
                 JSON.stringify(body, null, 4)
             );
 
             logger.error(context, 'Operation ' + operationName + ' error connecting to the Context Broker: %j', body);
-
-            const errorField = NGSIUtils.getErrorField(body);
-            if (response.statusCode && response.statusCode === 404 && errorField !== undefined) {
+            if ( NGSIUtils.getErrorField(body) !== undefined) {
                 callback(new errors.DeviceNotFound(entityName));
-            } else if (errorField.code && errorField.code === '404') {
-                callback(new errors.AttributeNotFound());
             } else {
                 callback(new errors.EntityGenericError(entityName, typeInformation.type, body));
             }

```

### entities-NGSI-LD.js


```diff
         } else if (response && body && response.statusCode === 404) {
             logger.info(context, 'Received the following response from the CB:\n\n%s\n\n', bodyAsString);
 
             logger.error(context, 'Operation ' + operationName + ' error connecting to the Context Broker: %j', body);
 
-            const errorField = NGSIUtils.getErrorField(body);
-            if (
-                response.statusCode &&
-                response.statusCode === 404 &&
-                errorField.details.includes(typeInformation.type)
-            ) {
+            if ( NGSIUtils.getErrorField(body) !== undefined) {
                 callback(new errors.DeviceNotFound(entityName));
-            } else if (errorField.code && errorField.code === '404') {
-                callback(new errors.AttributeNotFound());
             } else {
                 callback(new errors.EntityGenericError(entityName, typeInformation.type, body));
             }
```

- The second check for `response.statusCode && response.statusCode === 404` is redundant
- `errorField.code` is *not* defined under NGSI-v2 - hence the clause is unnecessary
- NGSI-LD changes should align with NGSI-v2 - it looks like they have diverged unnecessarily.

Making this change will not break the tests. Should I add it?

2021-09-01 14:42 UTC, jason-fox commented
Basically saying _If the broker response is a properly formed NGSI error response, then the device is not found_. If the broker response is a really nasty error with some random stack trace or something, log as a generic error.

2021-09-01 14:46 UTC, fgalan commented
> Making this change will not break the tests. Should I add it?

Maybe after these changes the NGSIUtils.getErrorField() function can be removed? It seems a remanent usage in lib/services/devices/registrationUtils.js stills, but maybe that part can be simplified.

2021-09-01 14:47 UTC, jason-fox commented
`NGSIUtils.getErrorField()`  **used** to be split into v1 and v2 versions and certainly can be refactored out.

2021-09-02 08:55 UTC, jason-fox commented
Fixed 2304aae - coverage drop now 0.5% or less.  I'm assuming the remaining drop is some NGSI-v1 stuff in the IoTManger and middlewares dealing with attributes.

2021-09-02 09:36 UTC, fgalan commented
> Fixed [2304aae](https://github.com/telefonicaid/iotagent-node-lib/commit/2304aaed427a2511adab805ae426e0457c3148f8) - coverage drop now 0.5% or less. I'm assuming the remaining drop is some NGSI-v1 stuff in the IoTManger and middlewares dealing with attributes.

Looking to the modifications in https://github.com/telefonicaid/iotagent-node-lib/compare/b1758c3...2304aae, I see getErrorField() has been removed along with two of its usages, in generateNGSI2OperationHandler() and generateNGSILDOperationHandler().

With regards to the third one I see at master within createRegistrationHandler() (https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/devices/registrationUtils.js#L57) I see you have removed the whole createRegistrationHandler() so that's fine :)

2021-09-02 09:44 UTC, jason-fox commented
The one in `createRegistrationHandler()` would have been for NGSI-v1 and would have called the `getErrorField()` for NGSI-v1. The other two would have been for NGSI-v2 and originally called ` getErrorFieldv2()` or something. Since v1 had been deleted ` getErrorFieldv2()` was renamed to ` getErrorField()` during the refactor. It has now been deleted.

2021-09-02 09:57 UTC, mapedraza commented
Great, all tests seems to be ported to V2. Now it is just pending a couple of pending reviews (related with nomenclature stuff):

- https://github.com/telefonicaid/iotagent-node-lib/pull/995#discussion_r671039851
- https://github.com/telefonicaid/iotagent-node-lib/pull/995#discussion_r671055058

After that, I think it is almos ready to merge

2021-09-02 10:07 UTC, jason-fox commented
Fixed 3be10f7

2021-09-02 10:23 UTC, mapedraza approved these changes
LGTM

2021-09-02 12:34 UTC, fgalan commented
The PR is in a good shape to start conducting e2e testing with IOTAs (+ Manager) generated from the following branches:

* https://github.com/telefonicaid/iotagent-json/pull/533
* https://github.com/telefonicaid/iotagent-ul/pull/467
* https://github.com/telefonicaid/sigfox-iotagent/pull/110
* https://github.com/telefonicaid/lightweightm2m-iotagent/pull/253
* https://github.com/telefonicaid/iotagent-manager/pull/238

In the meanwhile, this PR would need a CHANGES_NEXT_RELEASE entry. Suggestion:

```
- Remove: NGSI-v1 implementation (#966)
```

2021-09-02 12:40 UTC, jason-fox commented
Fixed 4a9fd4c

2021-09-03 08:41 UTC, fgalan commented
Good news. The CI e2e pass with the NGSIv1-removed versions went OK last night :)

So I think only this small issue is pending to do the merge: https://github.com/telefonicaid/sigfox-iotagent/pull/111#issuecomment-911631330

2021-09-15 13:27 UTC, fgalan approved these changes
LGTM. There is still some drop in coverage (around -0.7%) but it's acceptable (taking into account we come from a higher drop)

This PR will now be merged, followed by all the related ones in the IOTAs repositories. Thanks @jason-fox for this *huge* amount of work and also thanks to @mapedraza for his review work!

2021-09-15 13:28 UTC, merged